name: SAST Mobile

on:
  push:
    branches: ["staging"]
    paths-ignore: ["staging"]

env:
  COMMIT_SHA: ${{ github.sha }}
  REPO: frontend-mobile-edb

jobs:
  eslint:
    runs-on: ubuntu-latest
    environment: staging
    permissions:
      contents: read
      actions: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ESLint
        id: install-eslint
        run: |
          npm install eslint@8.10.0
          npm install @microsoft/eslint-formatter-sarif@2.1.7

      - name: Run ESLint
        id: run-eslint
        run: npx eslint ./src
          --config  eslint.config.mjs
          --format @microsoft/eslint-formatter-sarif
          --output-file eslint-result.sarif

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        id: upload-eslint-result
        if: success() || failure()
        with:
          sarif_file: eslint-result.sarif
          wait-for-processing: true

  sast-bearer-cli:
    needs: eslint
    continue-on-error: true
    runs-on: ubuntu-latest
    environment: staging
    permissions:
      contents: read
      actions: read
      security-events: write
      packages: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Bearer
        uses: bearer/bearer-action@v2
        id: run-bearer-scan
        with:
          format: sarif output: ${{ env.REPO }}-${{ env.COMMIT_SHA }}-security.sarif

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        id: upload-bearer-result
        if: success() || failure()
        with:
          sarif_file: ${{ env.REPO }}-${{ env.COMMIT_SHA }}-security.sarif
          wait-for-processing: true
