name: SAST Mobile

on:
  push:
    branches: ["staging"]
    paths:
      - "src/**"
      - ".github/workflows/**"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: belega-village-unud/backend-api-edb
  COMMIT_SHA: ${{ github.sha }}
  REPO: backend-api-edb
  INSTANCE_NAME: belega-instance
  ZONE: asia-southeast2-a

jobs:
  eslint:
    needs: setup
    runs-on: ubuntu-latest
    environment: staging
    permissions:
      contents: read
      actions: read
      security-events: write
      packages: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ESLint
        id: install-eslint
        run: |
          npm install eslint@8.10.0
          npm install @microsoft/eslint-formatter-sarif@2.1.7

      - name: Run ESLint
        id: run-eslint
        run: npx eslint ./src
          --config  eslint.config.js
          --format @microsoft/eslint-formatter-sarif
          --output-file eslint-result.sarif

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        id: upload-eslint-result
        if: success() || failure()
        with:
          sarif_file: eslint-result.sarif
          wait-for-processing: true
